const config=window.WOJIAYOUPU_CONFIG?.supabase||{};
const client=window.supabase.createClient(config.url,config.publishableKey,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
const params=new URLSearchParams(location.search);const token=params.get("token")||"";let email="";let countdown=0;let timer;
const $=selector=>document.querySelector(selector);
function show(id){for(const el of [$("#inviteLoading"),$("#inviteUnavailable"),$("#joinForm"),$("#otpForm")])el.classList.add("hidden");$(id).classList.remove("hidden")}
function message(id,text,error=false){const el=$(id);el.textContent=text;el.classList.toggle("error",error)}
async function call(body,authenticated=false){const{data:{session}}=await client.auth.getSession();const response=await fetch(`${config.url}/functions/v1/accept-invite`,{method:"POST",headers:{"Content-Type":"application/json",apikey:config.publishableKey,...(authenticated?{Authorization:`Bearer ${session?.access_token||""}`}:{})},body:JSON.stringify({...body,token})});const data=await response.json().catch(()=>({error:"服务返回异常"}));if(!response.ok||data.error)throw new Error(data.error||"请求失败");return data}
function startTimer(){clearInterval(timer);countdown=60;$("#resendOtp").disabled=true;$("#resendOtp").textContent=`${countdown} 秒后重发`;timer=setInterval(()=>{countdown-=1;$("#resendOtp").textContent=countdown>0?`${countdown} 秒后重发`:"重新发送";if(countdown<=0){clearInterval(timer);$("#resendOtp").disabled=false}},1000)}
async function completeFromSession(){const{data:{session}}=await client.auth.getSession();if(!session)return false;show("#otpForm");message("#otpMessage","邮箱验证成功，正在创建家族账号...");await call({phase:"complete"},true);history.replaceState({},"",location.pathname);message("#otpMessage","加入成功，正在进入家族空间");setTimeout(()=>location.assign("/"),600);return true}
async function requestOtp(){await call({phase:"request",name:$("#joinName").value.trim(),gender:$("#joinGender").value,email:$("#joinEmail").value.trim(),phone:$("#joinPhone").value.trim()});email=$("#joinEmail").value.trim().toLowerCase();$("#otpEmail").textContent=email;show("#otpForm");startTimer()}
try{const data=await call({phase:"inspect"});if(!data.available)throw new Error("邀请已过期、被撤销或家族暂不可用");$("#familyName").textContent=data.familyName;if(!await completeFromSession())show("#joinForm")}catch(error){$("#unavailableText").textContent=error.message;show("#inviteUnavailable")}
$("#joinForm").addEventListener("submit",async event=>{event.preventDefault();const button=event.submitter;button.disabled=true;message("#joinMessage","正在发送登录邮件...");try{await requestOtp()}catch(error){message("#joinMessage",error.message,true)}finally{button.disabled=false}});
$("#resendOtp").onclick=async()=>{try{await requestOtp();message("#otpMessage","登录邮件已重新发送")}catch(error){message("#otpMessage",error.message,true)}};
$("#otpForm").addEventListener("submit",async event=>{event.preventDefault();const button=event.submitter;button.disabled=true;message("#otpMessage","正在验证...");try{const otp=$("#joinOtp").value.trim();const{error}=await client.auth.verifyOtp({email,token:otp,type:"email"});if(error)throw error;await completeFromSession()}catch(error){message("#otpMessage",error.message||"验证码无效",true)}finally{button.disabled=false}});
