const config=window.WOJIAYOUPU_CONFIG?.supabase||{};
const client=window.supabase.createClient(config.url,config.publishableKey,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:false}});
const state={families:[],route:"dashboard",selectedFamily:null,detail:null,logs:[],session:null};
const $=selector=>document.querySelector(selector);const $$=selector=>[...document.querySelectorAll(selector)];
const titles={dashboard:["运营总览","管理家族、容量与成员访问权限"],families:["家族管理","开通、停用并调整家族容量"],accounts:["账号管理","配置家族成员角色和登录状态"],invites:["邀请管理","生成并管理家族邀请二维码"],audit:["审计日志","查看平台关键操作记录"],settings:["系统设置","配置新建家族和邀请的默认参数"]};

function normalizePhone(value){const raw=value.trim().replace(/[\s()+-]/g,"");return raw.startsWith("86")&&raw.length===13?raw.slice(2):raw}
function adminEmailFromPhone(value){const phone=normalizePhone(value);if(!/^1\d{10}$/.test(phone))throw new Error("请输入正确的管理员手机号");return `${phone}@admin.1000011.com`}
function escapeHtml(value){return String(value??"").replace(/[&<>\"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'\"':"&quot;"}[c]))}
function toast(message){const el=$("#toast");el.textContent=message;el.classList.add("show");clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.classList.remove("show"),2400)}
function setBusy(busy){$("#loadingState").hidden=!busy}function showError(message){$("#errorText").textContent=message;$("#errorState").hidden=false}
function hideStates(){$("#loadingState").hidden=true;$("#emptyState").hidden=true;$("#errorState").hidden=true}
function dateValue(value){return value?new Date(value).toISOString().slice(0,10):""}function dateLabel(value){return value?new Date(value).toLocaleDateString("zh-CN"):"长期"}
function statusLabel(value){return {active:"已启用",suspended:"已停用",expired:"已到期",archived:"已归档",disabled:"已停用",left:"已退出",revoked:"已撤销",exhausted:"已用尽"}[value]||value}
function roleLabel(value){return {owner:"负责人",admin:"家族管理员",editor:"编辑者",self_editor:"仅编辑本人",viewer:"只读"}[value]||value}

async function invoke(name,body){const{data:{session}}=await client.auth.getSession();const response=await fetch(`${config.url}/functions/v1/${name}`,{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${session?.access_token||""}`,apikey:config.publishableKey},body:JSON.stringify(body)});const payload=await response.json().catch(()=>({error:"服务返回异常"}));if(!response.ok||payload.error)throw new Error(payload.error||"请求失败");return payload}
async function ensureAdmin(session){if(!session)return false;const{data,error}=await client.from("platform_admins").select("status,must_change_password").eq("user_id",session.user.id).eq("status","active").maybeSingle();if(error||!data){await client.auth.signOut();return false}if(data.must_change_password)toast("首次登录后请尽快修改管理员密码");return true}
async function loadFamilies(){hideStates();setBusy(true);try{const data=await invoke("admin-family",{action:"list"});state.families=data.families||[];renderAll()}catch(error){showError(error.message)}finally{setBusy(false)}}
async function loadDetail(treeId){setBusy(true);try{state.detail=await invoke("admin-family",{action:"detail",treeId});state.selectedFamily=state.families.find(f=>f.id===treeId)||state.detail.family;renderFamilyDetail()}catch(error){toast(error.message)}finally{setBusy(false)}}
async function loadAudit(){try{const data=await invoke("admin-family",{action:"audit"});state.logs=data.logs||[];renderAudit()}catch(error){toast(error.message)}}

function usage(family,key){return Number(family.usage?.[key]||0)}function pct(count,limit){return limit?Math.round(count/limit*100):0}
function renderAll(){renderDashboard();renderFamilies();renderAudit()}
function renderDashboard(){const active=state.families.filter(f=>f.status==="active").length;const people=state.families.reduce((n,f)=>n+usage(f,"person_count"),0);const accounts=state.families.reduce((n,f)=>n+usage(f,"account_count"),0);$("#metrics").innerHTML=[["家族总数",state.families.length],["有效家族",active],["人物总数",people],["登录账号",accounts]].map(([label,value])=>`<div class="metric"><span>${label}</span><strong>${value}</strong></div>`).join("");const warnings=state.families.filter(f=>pct(usage(f,"person_count"),f.person_limit)>=80||pct(usage(f,"account_count"),f.account_limit)>=80);$("#warningRows").innerHTML=warnings.length?warnings.map(f=>`<tr><td>${escapeHtml(f.name)}</td><td class="usage warning">${usage(f,"person_count")} / ${f.person_limit}</td><td class="usage warning">${usage(f,"account_count")} / ${f.account_limit}</td><td class="status ${f.status}">${statusLabel(f.status)}</td></tr>`).join(""):`<tr><td colspan="4">暂无容量预警</td></tr>`}
function filteredFamilies(){const q=$("#globalSearch").value.trim().toLowerCase();const s=$("#familyStatusFilter").value;return state.families.filter(f=>(!s||f.status===s)&&(!q||`${f.code} ${f.name}`.toLowerCase().includes(q)))}
function renderFamilies(){const rows=filteredFamilies();$("#familyRows").innerHTML=rows.length?rows.map(f=>`<tr><td>${escapeHtml(f.code)}</td><td><strong>${escapeHtml(f.name)}</strong></td><td class="usage ${pct(usage(f,"person_count"),f.person_limit)>=80?"warning":""}">${usage(f,"person_count")} / ${f.person_limit}</td><td class="usage ${pct(usage(f,"account_count"),f.account_limit)>=80?"warning":""}">${usage(f,"account_count")} / ${f.account_limit}</td><td>${f.owner_user_id?"已绑定":"待认领"}</td><td class="status ${f.status}">${statusLabel(f.status)}</td><td>${dateLabel(f.expires_at)}</td><td><button class="row-action" data-open-family="${f.id}">管理</button></td></tr>`).join(""):`<tr><td colspan="8">没有符合条件的家族</td></tr>`}
function renderAudit(){const names=new Map(state.families.map(f=>[f.id,f.name]));$("#auditRows").innerHTML=state.logs.length?state.logs.map(log=>`<tr><td>${new Date(log.created_at).toLocaleString("zh-CN")}</td><td>${escapeHtml(log.action)}</td><td>${escapeHtml(log.target_type)}</td><td>${escapeHtml(names.get(log.tree_id)||"平台")}</td><td>${escapeHtml(log.actor_id.slice(0,8))}</td></tr>`).join(""):`<tr><td colspan="5">暂无审计记录</td></tr>`}

function renderFamilyDetail(){if(!state.detail)return;const f=state.detail.family;const members=state.detail.members||[];const invites=state.detail.invites||[];$("#accountContent").className="detail-stack";$("#accountContent").innerHTML=`<form class="family-config" id="familyConfigForm"><div class="detail-heading"><div><strong>${escapeHtml(f.name)}</strong><span>${escapeHtml(f.code)}</span></div><button class="button primary" type="submit">保存家族设置</button></div><div class="form-grid"><label>家族名称<input name="name" value="${escapeHtml(f.name)}" required></label><label>状态<select name="status"><option value="active">启用</option><option value="suspended">停用</option><option value="expired">到期</option><option value="archived">归档</option></select></label><label>人物容量<input name="person_limit" type="number" min="${state.detail.usage.person_count||1}" value="${f.person_limit}"></label><label>账号容量<input name="account_limit" type="number" min="${state.detail.usage.account_count||1}" value="${f.account_limit}"></label><label>套餐<input name="plan_name" value="${escapeHtml(f.plan_name)}"></label><label>到期日期<input name="expires_at" type="date" value="${dateValue(f.expires_at)}"></label></div></form><div class="table-wrap"><table><thead><tr><th>成员</th><th>邮箱</th><th>手机</th><th>角色</th><th>状态</th><th></th></tr></thead><tbody>${members.length?members.map(m=>`<tr><td>${escapeHtml(m.profile?.full_name||m.profile?.display_name||"未填写")}</td><td>${escapeHtml(m.profile?.normalized_email||"-")}</td><td>${escapeHtml(m.profile?.normalized_phone||"-")}</td><td><select data-member-role="${m.user_id}">${["owner","admin","editor","self_editor","viewer"].map(role=>`<option value="${role}" ${m.role===role?"selected":""}>${roleLabel(role)}</option>`).join("")}</select></td><td><select data-member-status="${m.user_id}"><option value="active" ${m.status==="active"?"selected":""}>启用</option><option value="disabled" ${m.status==="disabled"?"selected":""}>停用</option><option value="left" ${m.status==="left"?"selected":""}>退出</option></select></td><td><button class="row-action" data-save-member="${m.user_id}">保存</button></td></tr>`).join(""):`<tr><td colspan="6">尚无已加入账号</td></tr>`}</tbody></table></div>`;$("#familyConfigForm [name=status]").value=f.status;
  $("#inviteContent").className="detail-stack";$("#inviteContent").innerHTML=`<div class="detail-heading"><div><strong>${escapeHtml(f.name)}</strong><span>邀请链接仅在生成时显示，请及时保存二维码</span></div></div><div class="table-wrap"><table><thead><tr><th>类型</th><th>状态</th><th>使用次数</th><th>到期时间</th><th></th></tr></thead><tbody>${invites.length?invites.map(i=>`<tr><td>${i.default_role==="owner"?"负责人邀请":"成员邀请"}</td><td>${statusLabel(i.status)}</td><td>${i.used_count} / ${i.max_uses}</td><td>${dateLabel(i.expires_at)}</td><td>${i.status==="active"?`<button class="row-action danger" data-revoke-invite="${i.id}">撤销</button>`:"-"}</td></tr>`).join(""):`<tr><td colspan="5">暂无邀请</td></tr>`}</tbody></table></div>`;$("#createInviteBtn").disabled=false}
function showInviteResult(data,title){const qr=qrcode(0,"M");qr.addData(data.inviteUrl);qr.make();const qrUrl=qr.createDataURL(6,12);$("#inviteContent").className="invite-result";$("#inviteContent").innerHTML=`<img src="${qrUrl}" alt="${escapeHtml(title)}二维码"><div><strong>${escapeHtml(title)}</strong><p class="muted">扫码填写资料并验证邮箱后加入。邀请链接只显示本次，请立即保存。</p><input id="inviteUrl" value="${escapeHtml(data.inviteUrl)}" readonly><div class="invite-actions"><button class="button" id="copyInvite">复制链接</button><a class="button" href="${qrUrl}" download="family-invite.png">保存二维码</a><button class="button" data-refresh-detail>返回邀请列表</button></div></div>`;$("#copyInvite").onclick=()=>navigator.clipboard.writeText(data.inviteUrl).then(()=>toast("邀请链接已复制"));routeTo("invites")}
function routeTo(route){state.route=route;$$('.nav-item[data-route]').forEach(b=>b.classList.toggle("active",b.dataset.route===route));$$('.view').forEach(v=>v.classList.remove("active"));$(`#${route}View`).classList.add("active");const[title,sub]=titles[route];$("#pageTitle").textContent=title;$("#pageSubtitle").textContent=sub;if(route==="audit")loadAudit()}
async function openFamily(id){routeTo("accounts");await loadDetail(id)}
function modal(open){$("#modalBackdrop").hidden=!open;if(open){$("#familyForm").reset();$("#familyFormMessage").textContent="";$("#familyForm [name=personLimit]").value=$("#defaultPersonLimit").value;$("#familyForm [name=accountLimit]").value=$("#defaultAccountLimit").value}}

$("#adminLoginForm").addEventListener("submit",async event=>{event.preventDefault();const button=event.submitter;button.disabled=true;$("#loginMessage").textContent="";try{const{data,error}=await client.auth.signInWithPassword({email:adminEmailFromPhone($("#adminPhone").value),password:$("#adminPassword").value});if(error)throw error;if(!await ensureAdmin(data.session))throw new Error("账号没有平台管理权限");state.session=data.session;$("#loginScreen").hidden=true;$("#adminShell").hidden=false;await loadFamilies()}catch(error){$("#loginMessage").textContent=error.message||"登录失败"}finally{button.disabled=false}});
$("#adminSignOut").onclick=async()=>{await client.auth.signOut();location.reload()};$("#adminNav").onclick=e=>{const button=e.target.closest("[data-route]");if(button)routeTo(button.dataset.route)};
document.addEventListener("click",async e=>{const open=e.target.closest("[data-open-family]");if(open)await openFamily(open.dataset.openFamily);const jump=e.target.closest("[data-jump]");if(jump)routeTo(jump.dataset.jump);const save=e.target.closest("[data-save-member]");if(save){const userId=save.dataset.saveMember;try{await invoke("admin-family",{action:"member-update",treeId:state.selectedFamily.id,userId,role:$(`[data-member-role="${userId}"]`).value,status:$(`[data-member-status="${userId}"]`).value});toast("账号设置已保存");await loadDetail(state.selectedFamily.id)}catch(error){toast(error.message)}}const revoke=e.target.closest("[data-revoke-invite]");if(revoke){try{await invoke("family-invite",{action:"revoke",treeId:state.selectedFamily.id,inviteId:revoke.dataset.revokeInvite});toast("邀请已撤销");await loadDetail(state.selectedFamily.id)}catch(error){toast(error.message)}}if(e.target.closest("[data-refresh-detail]"))await loadDetail(state.selectedFamily.id)});
document.addEventListener("submit",async e=>{if(e.target.id!=="familyConfigForm")return;e.preventDefault();const form=new FormData(e.target);try{await invoke("admin-family",{action:"update",treeId:state.selectedFamily.id,name:form.get("name"),status:form.get("status"),person_limit:Number(form.get("person_limit")),account_limit:Number(form.get("account_limit")),plan_name:form.get("plan_name"),expires_at:form.get("expires_at")||null});toast("家族设置已保存");await loadFamilies();await loadDetail(state.selectedFamily.id)}catch(error){toast(error.message)}});
$("#globalSearch").oninput=renderFamilies;$("#familyStatusFilter").onchange=renderFamilies;$("#createFamilyBtn").onclick=()=>modal(true);$("#closeModal").onclick=()=>modal(false);$("#cancelModal").onclick=()=>modal(false);$("#retryBtn").onclick=loadFamilies;
$("#familyForm").addEventListener("submit",async event=>{event.preventDefault();const form=new FormData(event.currentTarget);const button=event.submitter;button.disabled=true;try{const data=await invoke("admin-family",{action:"create",name:form.get("name"),ownerEmail:form.get("ownerEmail"),personLimit:Number(form.get("personLimit")),accountLimit:Number(form.get("accountLimit")),planName:form.get("planName"),expiresAt:form.get("expiresAt")||null});modal(false);toast("家族已开通，负责人邀请已生成");await loadFamilies();state.selectedFamily=state.families.find(f=>f.id===data.family.id)||data.family;showInviteResult({inviteUrl:data.ownerInviteUrl},`${data.family.name}负责人邀请`)}catch(error){$("#familyFormMessage").textContent=error.message}finally{button.disabled=false}});
$("#createInviteBtn").onclick=async()=>{if(!state.selectedFamily)return;try{const days=Number($("#defaultInviteDays").value||7);const data=await invoke("family-invite",{action:"create",treeId:state.selectedFamily.id,maxUses:state.selectedFamily.account_limit,expiresAt:new Date(Date.now()+days*86400000).toISOString()});showInviteResult(data,`${state.selectedFamily.name}成员邀请`)}catch(error){toast(error.message)}};
for(const id of ["defaultPersonLimit","defaultAccountLimit","defaultInviteDays"]){const el=$(`#${id}`);el.value=localStorage.getItem(id)||el.value;el.onchange=()=>localStorage.setItem(id,el.value)}
const{data:{session}}=await client.auth.getSession();if(session&&await ensureAdmin(session)){state.session=session;$("#loginScreen").hidden=true;$("#adminShell").hidden=false;await loadFamilies()}
